[project]
name = "database"
version = "0.1.0"
description = "Add your description here"
readme = "510-software-engineering-7\\README.md"
requires-python = ">=3.14"
dependencies = [
    "bs4>=0.0.2",
    "openai>=2.7.1",
    "requests>=2.32.5",
]
